### ISSUE TITLE
rogue console.log in scion.js

### ISSUE THREAD

**Issue by mattoshry** [jbeard4/SCION-CORE#23]
Seeing the body of our transition listener in our service logs:

listener function (sourceStateId, targetIds) {
            if (targetIds && targetIds.length) {
                fsmLog('transitioning from ' + sourceStateId + ' to ' + targetIds.join(','));
            } else {
                fsmLog('executing target-less transition in ' + sourceStateId);
            }
        }

Looks like an accidental checkin as part of your recent registerListener fix

https://github.com/jbeard4/SCION-CORE/commit/533a9ec4d468bb4fc1dec38ec66923b5d052a3fb#diff-bc83a3f161f32c213ea899aba33cf6c7R387

**Comment by jbeard4** [comment]
Fixed in https://github.com/jbeard4/SCION-CORE/commit/342d582058f3be7c2169d7640e20dd3d8b1bc054
