### ISSUE TITLE
Demo on jsFiddle is broken

### ISSUE THREAD

**Issue by hdavidzhu** [jbeard4/SCION-CORE#25]
http://jsfiddle.net/jbeard4/MDkLe/2/

**Comment by jbeard4** [comment]
Working for me.


![](http://g.recordit.co/SZOPEWZAGg.gif)

**Comment by hdavidzhu** [comment]
Have you tried it in Chrome?

**Comment by jbeard4** [comment]
Confirmed broken in Chrome.

**Comment by jbeard4** [comment]
Fixed here: http://jsfiddle.net/jbeard4/MDkLe/11/

**Comment by jbeard4** [comment]
Documentation updated in ffc5fbc65f3d1a0bbda4554a0b5e399113de9447

**Comment by jbeard4** [comment]
@hdavidzhu Thank you for reporting this.
