### ISSUE TITLE
Impossible to retrieve global state from snapshot

### ISSUE THREAD

**Issue by Sneko** [jbeard4/SCION-CORE#49]
@jbeard4 Hi!

I have made a statechart with 3 states (a/b/c with "a" one the init state), then I trigger some events to move inside and finally I store the snapshot in my app.

But when I prepare a new instance of the statechart with previous snapshot, it appears that's the statechart is in initial state (a) after starting.

Could you confirm that this feature is working please?

I have checked the "this._configuration" in the BaseInterpreter constructor and it's the data matched to be directly in "c" state : 
`{ o: 
   Set {
     { id: 'c',
     actions: [Array],
     transitions: [Array],
     '$type': 'state',
     ancestors: [Array],
     depth: 2,
     parent: [Object],
     documentOrder: 8,
     typeEnum: 0,
     descendants: [] } } }
`

Thanks!

**Comment by jbeard4** [comment]
Hi,

Make sure you're using something like the following pattern:

```javascript
function handleEvent(snapshot, event){
  
  let interpreter
  if(!snapshot){
    //instantiate the interpreter
    interpreter = new scxml.scion.Statechart(fnModel);
    //start the interpreter
    interpreter.start();
  }else{
    //instantiate the interpreter, and rehydrate the snapshot
    interpreter = new scxml.scion.Statechart(fnModel, {snapshot : snapshot});
  }

  //process event
  interpreter.gen(event); 

  //return new snapshot
  return interpreter.getSnapshot();
}
```

**Comment by jbeard4** [comment]
Please re-open this issue if you encounter additional difficulties with this API.

**Comment by Sneko** [comment]
Hi @jbeard4 !

Thanks for your answer, it led me to the solution :) : I was calling interpreter.start() even after instanciating interpreter with snapshot.

You have done a really good job with this plugin, thanks!

**Comment by jbeard4** [comment]
I will update the README with better instructions. Thanks for your feedback.
