### ISSUE TITLE
Getting event data parameter in listeners

### ISSUE THREAD

**Issue by CsabaBarsony** [jbeard4/SCION-CORE#54]
Is it possible to access event data in listeners, not only the state id?

I tried something like this:
`sc.on('onEntry', function(stateId, data) {
    console.log(data) // need access to event's data somehow
})`

**Comment by jbeard4** [comment]
You can do it like this:

```javascript
let lastEvent;
sc.on('onSmallStepBegin', function(event){
  lastEvent = event;
})

sc.on('onEntry', function(stateId) { 
  console.log(lastEvent.data) 
})
```

**Comment by CsabaBarsony** [comment]
Thanks, it's working!

**Comment by jbeard4** [comment]
Great
