### ISSUE TITLE
sc.isFinal()

### ISSUE THREAD

**Issue by Getafix-hub** [jbeard4/SCION-CORE#56]
Hi, 

Could you provide an example of a JSON statechartModel with a final state? 

I tried something like this without success (sc.isFinal() always returned false) 
` 
{
    id: 'state2',
    isInFinalState: true,
    onEntry: function () {
        console.log('state2');
    },
    transitions: []
}
`

Thanks

**Comment by jbeard4** [comment]
Use attribute `$type:'final'` in the state object. This needs to be better documented.

Thanks.

**Comment by chrgrd** [comment]
thank you
